deploy:
  provider: heroku
  api_key:
    secure: AtQU2582cXaNy3MdL4Ejhbv/ofdMJJ14E4gWyHOwg1uspVZApf/ZwfKRD9zbdZA16rOhIW7Ve/54EVsuCqKsKHY+CY/2+tWZs9Irbst0p5tbbxslUUAImDj5fuhnLfVi+j+ja1wTZ/esMe6aPMpCpwwxLb6/UTFCSPWvRhIsbQ7CVpsL84kEc08qYSX3AxCtiM7xXITbvq1qIlxXBlil7mbixRO64ajIF2hAL2nUFyY4UkubouJC6e96KlyKc1d64+bSR4krl+2hIcm6xXK0mwPVhRslm2qXxAkayzqa6IR6a+2ySjsMOWxA/GjTOuH6UwhUoo44IaJcAcXbDTlRZPcw7Puta4vYrVDGcGYsdyQ3ljVqBl/go8QEBfextHSb0PR+fONvdywtP6cTUw8GVItKmEeWI6Kq46hHJ6qq8iUKH/XZKb78gVIAv4zF09oj9IvwXG+SyS5smK0wOuXQC71CneDHGd4xRHQ2iQWKkgVo3gUwgTxD/+nMLctIYMZhInnTxEq36FVqqzm4OdQj3jYG80kIKMv0c0hODIyeBAlNyaYV5uWHAytWaqhG/sC3se2NFo8S5HqVQ8plFhr97hCmHKCXTVAzZu+PcDfSdt1lpUb81Hf/3EUNuXJssGvDtbK4P7TakL9fP7qe+dQ3ma704U2RpiVJgmDmfFmtSzw=
  app: radarr-sonarr-discord-webhook
  on:
    repo: dylanjboyd/radarr-sonarr-discord-webhook
language: node_js
node_js:
  - "lts/*"